### ISSUE TITLE
Feature request: Ability to specify which custom template you want to use

### ISSUE THREAD

**Issue by jack-chapman** [hosein2398/gue#1]
When I create a component with `gue my-component`, it would be really helpful to be able to specify a specific custom template to use. e.g. I might want to use a different custom template to generate a simple UI component compared to a dashboard page.

`-t` could be used to signify a non-default custom template is to be used.

`gue my-component -t component` - create using my 'component' template

`gue admin-dashboard -t page` - create using my 'page' template

an object containing templates and their names could be supplied in `gue.json`:

```json
{
  "componentSource": {
    "component": "./myTemplates/component.vue",
    "page": "./myTemplates/page.vue",
  },
}
```

**Comment by hosein2398** [comment]
This is great.
And I'll implement it I guess.

**Comment by hosein2398** [comment]
There is a thing though, If someone adds couple of templates he won't be using them equally and there are chances that he'll use one template often, so there should be a default template that whenever user types `gue foo` (without any parameters), Gue picks that default component.
Maybe this can be achieved like so:
```
{
  "componentSource": {
    "component:default": "./myTemplates/component.vue",
    "page": "./myTemplates/page.vue",
  },
}
```
So that whenever `gue bazz` is written `component` is used. And we've made command smaller and removed `-t component`

**Comment by jack-chapman** [comment]
> there should be a default template that whenever user types `gue foo` (without any parameters), Gue picks that default component.

Sounds good to me!

**Comment by hosein2398** [comment]
done! 
https://github.com/hosein2398/gue#using-multiple-custom-templates
